### ISSUE TITLE
Version Catalog code snippets

### ISSUE THREAD

**Issue by trevjonez** [gradle/plugin-portal-requests#174]
Add version catalog examples to the plugin portal gui.

### Expected Behavior

transform the ID as the default name?
for example [jetbrain tf plugin](https://plugins.gradle.org/plugin/org.jetbrains.gradle.terraform) might look like this:
```toml
[plugins]
org-jetbrains-gradle-terraform = { id = "org.jetbrains.gradle.terraform", version = "1.4.2" }
```

and maybe link to the [gradle version catalog toml documentation](https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format)

### Context

Make pulling in another plugin faster while also encouraging people to use version catalogs.
